PLATFORM_KEY=mac
PLATFORM_NAME="Apple Macintosh"
FX_ARCH=mac
INSTALLER_PFX=fas21-
INSTALLER_SFX=.dmg
INSTALLER_XTR=
DSPORD=3
LAUNCH_PATH=/Applications/fas21.app/Contents/MacOS/
JAVA_CMD=fas21.app/Contents/MacOS/fas21
